_format_version: "3.0"
consumers:
- keyauth_credentials:
  - key: "190724"
  username: my-client-app
- jwt_secrets:
  - algorithm: HS256
    key: JSqiTVQalVBu6Uyz3s8ypeR0KBTFfKws
    secret: k4wMZ1floYXNq7RwvFKMQJ7Ap6SCMuhm
  username: tesser
- jwt_secrets:
  - algorithm: HS256
    key: nAmpayZ0SdSUMBL8RSLfzP0f0HsxP17D
    secret: dBbCyKzkq6gLVwfVdqZEEzVDjvqyAEpC
  username: test2ser
- jwt_secrets:
  - algorithm: HS256
    key: jUPhcOcniKrzllwLHMg4TTS5R7DvDhjY
    secret: tyrvCzRHu7eSyKkLKosuiDw5a3vncczk
  username: test62ser
- jwt_secrets:
  - algorithm: HS256
    key: IuiK3x8mVrz9Pi2eY27dXZpgEl1d9T0S
    secret: W5JhTHVhRAFp9Rh2JZt4eGJOMSoAVtXX
  username: testa2ser
- jwt_secrets:
  - algorithm: HS256
    key: natHpNQcrwaLyGnyPudodn0KwOT88aWA
    secret: 0GwmiVzK2Jj1SIIwf9iDG0EoETy2h453
  username: testuser
- jwt_secrets:
  - algorithm: HS256
    key: 7b8iXrZGsZlT5peSesQMC6FdMl0urCqp
    secret: luQ1mb50QyL4vXfG3XYU2cHTcnA9agwS
  username: tesxta2ser
plugins:
- config:
    content_type: application/json
    custom_fields_by_lua: null
    flush_timeout: null
    headers: null
    http_endpoint: http://host.docker.internal:4000/logs
    keepalive: 60000
    method: POST
    queue:
      concurrency_limit: 1
      initial_retry_delay: 0.01
      max_batch_size: 1
      max_bytes: null
      max_coalescing_delay: 1
      max_entries: 10000
      max_retry_delay: 60
      max_retry_time: 60
    queue_size: null
    retry_count: null
    timeout: 10000
  enabled: true
  name: http-log
  protocols:
  - grpc
  - grpcs
  - http
  - https
services:
- connect_timeout: 60000
  enabled: true
  host: host.docker.internal
  name: node-api
  path: /
  plugins:
  - config:
      content_type: application/json
      custom_fields_by_lua: null
      flush_timeout: null
      headers: null
      http_endpoint: http://host.docker.internal:4000/logs
      keepalive: 10000
      method: POST
      queue:
        concurrency_limit: 1
        initial_retry_delay: 0.01
        max_batch_size: 1
        max_bytes: null
        max_coalescing_delay: 1
        max_entries: 10000
        max_retry_delay: 60
        max_retry_time: 60
      queue_size: null
      retry_count: null
      timeout: 10000
    enabled: true
    name: http-log
    protocols:
    - grpc
    - grpcs
    - http
    - https
  - config:
      anonymous: null
      hide_credentials: false
      key_in_body: false
      key_in_header: true
      key_in_query: true
      key_names:
      - apikey
      realm: null
      run_on_preflight: true
    enabled: true
    name: key-auth
    protocols:
    - grpc
    - grpcs
    - http
    - https
  - config:
      day: null
      error_code: 429
      error_message: API rate limit exceeded
      fault_tolerant: true
      header_name: null
      hide_client_headers: false
      hour: null
      limit_by: consumer
      minute: 5
      month: null
      path: null
      policy: local
      redis:
        database: 0
        host: null
        password: null
        port: 6379
        server_name: null
        ssl: false
        ssl_verify: false
        timeout: 2000
        username: null
      redis_database: 0
      redis_host: null
      redis_password: null
      redis_port: 6379
      redis_server_name: null
      redis_ssl: false
      redis_ssl_verify: false
      redis_timeout: 2000
      redis_username: null
      second: null
      sync_rate: -1
      year: null
    enabled: true
    name: rate-limiting
    protocols:
    - grpc
    - grpcs
    - http
    - https
  port: 4000
  protocol: http
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    id: 29f7b8c6-ebcf-4ed2-8a4b-51fb1a755134
    methods:
    - POST
    path_handling: v0
    paths:
    - /logs
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  - https_redirect_status_code: 426
    id: 516a5f5e-43b1-46fb-bbcb-07c929047eb4
    methods:
    - POST
    path_handling: v0
    paths:
    - /logs
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  - https_redirect_status_code: 426
    id: d9695745-e8dd-484f-8332-936ed91ee128
    methods:
    - POST
    path_handling: v0
    paths:
    - /logs
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  - https_redirect_status_code: 426
    name: node-api-route
    path_handling: v0
    paths:
    - /api
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
  write_timeout: 60000
